api_version: v1
kind: plugin
metadata:
  name: python-plugin-template
  description: A template Python plugin for Dify that demonstrates basic functionality
spec:
  runtime: python3.10
  dependencies:
    - requests==2.31.0
    - pydantic==2.5.2
  api:
    http:
      # Main endpoint for the plugin
      process:
        path: /process
        method: POST
        response_schema:
          type: object
          properties:
            success:
              type: boolean
            message:
              type: string
            data:
              type: object
    configuration:
      - name: api_key
        type: secret
        required: true
        description: API key for authentication
      - name: max_retries
        type: number
        required: false
        default: 3
        description: Maximum number of retries for API calls 